config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'static#home'
  post '/sessions', to: 'sessions#create'

  get '/login', to: 'sessions#new'

  resources :events do 
    resources :dishes, only: [:create, :destroy]
  end

  resources :comments, only: [:create]
  resources :event_dishes, only: [:update]

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :event_dishes, dependent: :destroy
  has_many :events, through: :event_dishes
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_dishes
  has_many :dishes, through: :event_dishes
  has_many :comments

  def unclaimed_dishes
    event_dishes.where(claimed: false)
  end

  def claimed_dishes
    event_dishes.where(claimed: true)
  end

end

app/models/event_dish.rb
class EventDish < ApplicationRecord
  belongs_to :dish
  belongs_to :event
  belongs_to :user, optional: true
end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
  has_many :events
  has_many :comments
  has_secure_password

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.password = SecureRandom.hex
      user.image = auth.info.image
      user.name = auth.info.name
      user.facebook_oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    event = Event.find(params[:event_id])
    comment = current_user.comments.build(comment_params)
    comment.event = event

    if comment.save
      redirect_to event
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :event_id)
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @dish = @event.dishes.build(dish_params)
    ed = @event.event_dishes.build(dish: @dish, user: current_user, claimed: true)
    if @event.save && ed.save
      redirect_to @event
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    dish = Dish.find(params[:id])
    if dish.destroy
      redirect_to event
    end
  end

  private
    def dish_params
      params.require(:dish).permit(:name)
    end
end

app/controllers/event_dishes_controller.rb
class EventDishesController < ApplicationController
  before_action :set_event_dish, only: [:update]

  def update
    @event_dish.update(claimed: true, user: current_user)
    redirect_to @event_dish.event
  end

  private
    def set_event_dish
      @event_dish = EventDish.find(params[:id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy, :update]

  def index
    if logged_in? 
      @events = Event.where('date > ?', Date.today).order(:date => :asc)
    else
      redirect_to login_path
    end
  end

  def new
    @event = Event.new
  end

  def create
    event = current_user.events.build(event_params)

    if event.save
      redirect_to event
    else
      redirect_to new_event_path
    end
  end

  def update
    ed = @event.event_dishes.build(dish_id: params[:dish_id], user: current_user, claimed: true)
    if ed.save
      redirect_to @event
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path
    end
  end

  def show
    if !logged_in?
      redirect_to login_path
    end
    @comment = current_user.comments.build
    @comments = @event.comments.order(created_at: :desc)
    @dishes  = Dish.all
  end

  private
    def event_params
      params.require(:event).permit(:text, :date, :street, :city, :state, :zip)
    end

    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if request.env["omniauth.auth"]
      user = User.from_omniauth(request.env["omniauth.auth"])

      if user.valid?
        session[:user_id] = user.id
        redirect_to events_path
      end
    else
      user = User.find_by(email: params[:user][:email])
      
      if user && user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to events_path
      else
        redirect_to login_path
      end
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    if logged_in?
      redirect_to events_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to events_path
    else
      redirect_to new_user_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/event_dishes_helper.rb
module EventDishesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1 class="uk-heading-primary">All Upcoming Events</h1>

<ul class="uk-list">
  <% @events.each do |event| %>
    <li><%= link_to event.text, event %> - <%= event.date.strftime("%b %e, %l:%M %p") %> <% if event.user == current_user %>- <%= link_to "Delete Event", event_path(event), method: 'delete' %> <% end %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<div class="module">
<h3 class="uk-heading-line"><span>Create an Event</span></h3>

  <%= form_for @event, html: {class: 'uk-form-stacked'} do |f| %>
    <%= f.label "Event", class: 'uk-form-label' %>
    <%= f.text_field :text, class: 'uk-input', placeholder: "ex. Christmas 2017", :required => true %>
    <%= f.label "Date: (format 2/25/2017, 05:00 PM)", class: 'uk-form-label' %>
    <%= f.datetime_field :date, class: 'uk-input', :required => true, placeholder: "12/25/2017, 05:00 PM" %>
    <%= f.label :location, class: 'uk-form-label' %>
    <%= f.text_field :location, class: 'uk-input', placeholder: "ex. Bantados Residence", :required => true %>
    <%= f.label "Person to Contact for more Info", class: 'uk-form-label' %>
    <%= f.text_field :contact, class: 'uk-input', placeholder: "ex. Onofre Bantados", :required => true %>
    <br />
    <br />
    <%= f.submit 'Create Event', class: 'uk-button uk-button-primary' %>
  <% end %>
</div>

<%= stylesheet_pack_tag 'form' %>

app/views/events/show.html.erb
<div class="uk-grid-match uk-child-width-1-3@m" uk-grid>

<div>
  <div class="uk-card uk-card-hover uk-card-default uk-card-primary", style="background-color: #3498db;">
    <div class="uk-card-header">
      <div class="uk-grid-small uk-flex-middle" uk-grid>
        <div class="uk-width-auto">
          <h3 class="uk-card-title uk-margin-remove-bottom">
            <%= @event.text %> <span class="uk-text-meta">(<%= @event.date.strftime("%b %e, %l:%M %p") %>)</span>
          </h3> 
        </div>
      </div>
    </div>
    <div class="uk-card-body">
      <h4 class="uk-card-title uk-margin-remove-bottom uk-margin-remove-top">Information:</h4>
      Location: <%= @event.location %><br/>
      Contact Person: <%= @event.contact %>      
    </div>
  </div>
</div>
  <div>
    <div class="uk-card uk-card-hover uk-card-default uk-card-default">
      <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-auto">
            <h3 class="uk-card-title uk-margin-remove-bottom">
              Previous Dishes
            </h3> 
          </div>
        </div>
      </div>
      <div class="uk-card-body">
        <div class="uk-child-width-1-2@s uk-grid-collapse uk-text-center" uk-grid>
          <% @dishes.sort{|a, b| a.name <=> b.name }.each do |dish| %>
            <% if !@event.dishes.include?(dish) %>
            
            <div class="uk-tile uk-padding-small uk-tile-default">
            <%= dish.name.split.map(&:capitalize).join(' ') %>  
            <%= form_for(@event) do |f| %>
              <%= hidden_field_tag :dish_id, dish.id %>
              <%= f.submit "I'll Bring It!", class: 'uk-button-mini uk-button-secondary' %>
            <% end %>
            <% if current_user.admin %>
              <%= button_to "Delete", event_dish_path(@event, dish), method: :delete %>
            <% end %>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    <div>
    <div class="uk-card uk-card-hover uk-card-default uk-card-primary", style="background-color: #27ae60;">
      <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-auto">
            <h3 class="uk-card-title uk-margin-remove-bottom">
              New Dish
            </h3> 
          </div>
        </div>
      </div>
      <div class="uk-card-body">
        
        <%= form_for ([@event, Dish.new]) do |f| %>
          <%= f.label "Dish Name", class: 'uk-form-label' %>
          <%= f.text_field :name, class: 'uk-input-small' %>
          <%= f.submit 'Add Dish', class: 'uk-button-mini uk-button-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="uk-grid-match uk-child-width-1-2@m" uk-grid>
  <div>
    <div class="uk-card uk-card-hover uk-card-default uk-card-default uk-text-center">
      <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-auto">
            <h3 class="uk-card-title uk-margin-remove-bottom">
              Dishes claimed
            </h3> 
          </div>
        </div>
      </div>
      <div class="uk-card-body">
        <ul class="uk-list">
          <% @event.claimed_dishes.each do |ed| %>
            <li><%= ed.dish.name.split.map(&:capitalize).join(' ') %> - <%= ed.user.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div>
    <div class="uk-card uk-card-hover uk-card-default uk-card-default">
      <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-auto">
            <h3 class="uk-card-title uk-margin-remove-bottom">
              Comments
            </h3> 
          </div>
        </div>
      </div>
      <div class="uk-card-body">
        <%= form_for(@comment) do |f| %>
          <%= f.text_field :content, class: 'uk-input', placeholder: "add a comment", :required => true %>
          <%= hidden_field_tag :event_id, @event.id %>
        <% end %>
        <ul class="uk-comment-list"> 
          <% @comments.each do |c| %>
            <li style="margin-top: 20px;">
              <article class="uk-comment uk-visible-toggle">
                <header class="uk-comment-header uk-position-relative">
                    <div class="uk-grid-medium uk-flex-middle" uk-grid>
                        <div class="uk-width-auto">
                            <img class="uk-comment-avatar" src="<%= c.user.image %>" width="80" height="80" alt="">
                        </div>
                        <div class="uk-width-expand">
                            <h4 class="uk-comment-title uk-margin-remove"><%= c.user.name %></h4>
                            <p class="uk-comment-meta uk-margin-remove-top"><%= time_ago_in_words(c.created_at) %> ago</p>
                        </div>
                    </div>
                </header>
                <div class="uk-comment-body">
                    <%= c.content %>
                </div>
            </article>
            <hr class="uk-divider-small" />
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h3 class="uk-heading-line"><span>Create an Account</span></h3>

  <%= form_for @user, html: {class: 'uk-form-stacked'} do |f| %>
    <%= f.label :name, class: 'uk-form-label' %>
    <%= f.text_field :name, class: 'uk-input', :required => true %>
    <%= f.label :email, class: 'uk-form-label' %>
    <%= f.text_field :email, class: 'uk-input', :required => true %>
    <%= f.label :password, class: 'uk-form-label' %>
    <%= f.password_field :password, class: 'uk-input' %>
    <br />
    <br />
    <%= f.submit 'Create Account', class: 'uk-button uk-button-primary' %>
  <% end %>
</div>

<%= stylesheet_pack_tag 'form' %>